# Generated by Django 4.0.4 on 2022-06-26 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_example', models.ImageField(upload_to='face_examples/')),
                ('name', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=20)),
                ('embedding', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='VideoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video_example/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('emotions', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
